### Process data into correct format

In [33]:
import numpy as np
import pandas as pd

#df_Train = pd.read_csv('/Users/Steve/Desktop/Titanic dataset/TitanicTrain.csv')
df_Train = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTliZmavBsJCFDiEwxcSIIftu-0gR9p34n8Bq4OUNL4TxwHY-JMS6KhZEbWr1bp91UqHPkliZBBFgwh/pub?gid=1593012114&single=true&output=csv')
df_Test = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRqbQjIAiSmvJuNfcxBuxnKqOrwN82w0o27K3HYbD2DWUmsWuKKGYqKFj7hEUgJ2FqeSolBnDUqGoUc/pub?gid=471563808&single=true&output=csv')

#Create dataframe with numeric categorical features & outcomes. 
df_all =pd.get_dummies(df_Train,columns=['Sex', 'Embarked', 'Pclass', 'Survived'], drop_first=True)

#Convert dataframe to numpy array containing my basic list of features to use.
X_train = df_all[['Sex_male','Pclass_2', 'Pclass_3','Embarked_Q', 'Embarked_S']].values

#Create the "survival outcome" dataframe and then convert it to numpy array/series.
y_train = df_all['Survived_1'].values


### Decision Tree Model

In [34]:
from sklearn import metrics
#instantiate Model
clf = DecisionTreeClassifier(random_state=1)

#Fit model 
clf.fit(X_train, y_train)

#Predict survival using model
predicted_survival = clf.predict(X_train)
actual_survival = y_train

#check Decision tree  performance
print(metrics.confusion_matrix(actual_survival, predicted_survival))

[[523  26]
 [142 200]]


### Support Vector Machine

In [35]:
from sklearn.svm import SVC
model3 = SVC(gamma=2, C=1)
model3.fit(X_train, y_train)
prediction3 = model3.predict(X_train)
observed3 = y_train
print(metrics.confusion_matrix(observed3, prediction3))

[[523  26]
 [142 200]]


### Neural Network (MLP Classifier)

In [36]:
from sklearn.neural_network import MLPClassifier
model2 = MLPClassifier(hidden_layer_sizes=(30,30,30))
model2.fit(X_train, y_train)
prediction2 = model2.predict(X_train)
observed2 = y_train
print(metrics.confusion_matrix(observed2, prediction2))

[[523  26]
 [142 200]]
